### ISSUE TITLE
Please document recommended order of export/import to avoid dependency issues

### ISSUE THREAD

**Issue by smashism** [jamfprofessionalservices/JamfMigrator#12]
Hey team, the readme mentions that there are a lot of dependencies when running the migrator. Can you please post a recommended order for the migrator tool so that the tool can be used more efficiently? Just like "we recommended packages first, then scripts, then policies" or whatever the case may be. This would be very beneficial information to have. Thanks.

**Comment by BIG-RAT** [comment]
This is the order I'd suggest for migrating endpoints:
**General**:
    sites, userextensionattributes, users, buildings, departments, categories, ldapservers, jamfusers, jamfgroups, networksegments, advancedusersearches, usergroups
**macOS**:
    distributionpoints, directorybindings, dockitems, computers, softwareupdateservers, netbootservers, computerextensionattributes, advancedcomputersearches, scripts, computergroups, osxconfigurationprofiles, packages, printers, computerconfigurations, policies.
**iOS**:
    mobiledeviceextensionattributes, mobiledevices, mobiledevicegroups, advancedmobiledevicesearches, mobiledeviceconfigurationprofiles. 

I'll look to update the documentation.

**Comment by BIG-RAT** [comment]
Added to help.

**Comment by smashism** [comment]
Thanks for adding this to the help menu! Only issue is you can't leave the help menu open while using jamf migrator, so you can't keep the list up to reference. Any chance that can be documented on this repo, maybe in the wiki or something? That may be more functional.
