### ISSUE TITLE
 "Jamf Groups" are migrated before the "LDAP Servers"

### ISSUE THREAD

**Issue by macmule** [jamfprofessionalservices/JamfMigrator#14]
Hi folks,

In the below example, the "Jamf Groups" are migrated before the "LDAP Servers".

![screenshot 2018-01-13 12 48 49](https://user-images.githubusercontent.com/2464974/34906201-1fce7ffa-f860-11e7-91ce-5a1cee371c9c.png)

This leads the "Jamf Groups" to fail, but if you click "Go!" again the "Jamf Groups" will succeed as the "LDAP Servers" will have entries.

**Comment by BIG-RAT** [comment]
Modified concurrent tasks to better preserve desired order of operations.  Let me know how things work out as time permits.
