### ISSUE TITLE
v2.8.2 quits while migrating iOS Smart Groups

### ISSUE THREAD

**Issue by richard-datajar** [jamfprofessionalservices/JamfMigrator#20]
When attempting to migrate iOS smart groups in version 2.8.2, JamfMigrator will quite.

I have tested the previous version ,2.7.2 and this still works as expected.

The error seems to be on line 2477 inside ViewConroller.swift. 

 let localTmp = (self.counters[endpointType]?["fail"])!

This seems to be nil, which is causing the implicit unwrapping to fail.

**Comment by BIG-RAT** [comment]
Looks like if the first group to migrate fails the app would crash.  Let me know if the crash still occurs with the [update](https://github.com/jamfprofessionalservices/JamfMigrator/releases/download/current/jamf-migrator.zip) - thanks.
