### ISSUE TITLE
Scripts not uploading to jamfcloud instance

### ISSUE THREAD

**Issue by smashism** [jamfprofessionalservices/JamfMigrator#22]
We have a relatively new JamfCloud instance and we are trying to use jamf-migrator to migrate scripts from an on-prem Jamf Pro instance to our cloud instance. Only 7 of the scripts upload. The 100+ others don't and throw 409 errors. git2jss has the same issue, so I'm guessing it's some kind of error handling or API related thing with jamfcloud.

**Comment by smashism** [comment]
Looks like I get 409s for two primary reasons:
- Category the script is in doesn't exist in the target JSS
- EAs that have `?` (or potentially other special characters) in the name

Would it be possible to include some error handling for these situations? Maybe if a category isn't available put the script in `None`?

**Comment by BIG-RAT** [comment]
Good idea.  I'll fix it so if the category is not there it sets it to none.  This should apply to anything missing a category like policies.  I'll try to do the same for buildings and departments.  Tackle the special chars in the name next.

**Comment by BIG-RAT** [comment]
Category, building, and department will be dropped if they do not exist on the destination server.  Couldn't replicate the issue with a ? in the name of an extension attribute.  I get the following in the log, and verified the EA was created on the destination server.

20181109_17:16:57 [CreateEndpoints] [computerextensionattributes] succeeded: test - !@#$%^&amp;*
20181109_17:16:57 [CreateEndpoints] [computerextensionattributes] succeeded: test - ?

Wonder if I could get the XML from one of the EAs that failed.
