### ISSUE TITLE
Policies are not associated with other identifying criteria

### ISSUE THREAD

**Issue by rtrouton** [jamfprofessionalservices/JamfMigrator#4]
I would like to request that policies appear in the `Selective` list with more information than just the policy name. 

The reason I'm requesting this is that I have a number of policies that are identically named. For example, I have two policies in Self Service named `Google Chrome`:

- One `Google Chrome` installs Google Chrome and is scoped to include machines that don't have Google Chrome installed. 
- The other `Google Chrome` policy uninstalls Google Chrome and is scoped to include machines that do have Google Chrome installed.

This provides a simple way for my users to tell if they have Google Chrome installed, and take the appropriate action.

**Comment by BIG-RAT** [comment]
Policies are now displayed along with their jss ID to distinguish one from another.
