### ISSUE TITLE
Possible typo in readme.md

### ISSUE THREAD

**Issue by acodega** [jamfprofessionalservices/JamfMigrator#7]
> Note: the app can also be used to clear out a Jamf server. Typing the following after launching the app will remove items from the destination server.

Should this say from the source server, and which server should the command be run from?

> touch ~/Library/Application\ Support/jamf-migrator/DELETE

**Comment by BIG-RAT** [comment]
Command is run from the machine running the migrator app.  Then when the 'migration' is performed (Go button) rather then migrating some/all items from source to destination they are removed from the destination server.
